### ISSUE TITLE
fluxDomainManager

### ISSUE THREAD

**Issue by Stjoo0925** [Flux2024/Flux_BackServer#13]
관리자 페이지 도메인 작성

**Comment by KHY90** [comment]
아티클 등록 페이지 작성중

**Comment by KHY90** [comment]
아티클 등록에서 계속 보안관련 에러로 연결이 안되고 있습니다 ㅠㅠ
혹시 심심하신분 한번 도전해보시는건....ㅋㅋㅋㅋ
